#!/bin/bash

info_sh="${1:-${CETPKG_BUILD:-.}}/cetpkg_info.sh"

# Source the environment to verify.
. "${info_sh}" || \
  { echo "unable to build environment from $info_sh" 1>&2; exit 1; }

printf "To inspect build variable settings, execute ${info_sh}\n\n";

failed=()
check=(NAME VERSION)
[ -z "$CETPKG_NOARCH" ] && check+=(QUALSPEC BUILD_TYPE)
check_env=(BUILD SOURCE)

for cet_var in "${check[@]}"; do
  eval "[ -n \"\${CETPKG_$cet_var+x}\" ]" || failed+=("$cet_var")
done

# Complain for undefined variables.
(( ${#failed[@]} > 0 )) && cat 1>&2 <<EOF && exit 1
ERROR: unexpected undefined shell variable(s):
         ${failed[*]}
EOF

for cet_env in "${check_env[@]}"; do
  printenv CETPKG_$cet_env >/dev/null 2>&1 || failed+=("$cet_env")
done

# Complain for undefined environment variables.
(( ${#failed[@]} > 0 )) && cat 1>&2 <<EOF && exit 1
ERROR: unexpected undefined environment variable(s):
         ${failed[*]}
EOF

[ -n "${CETPKG_INSTALL}" ] || install_args=(-I "<ups-topdir>")

if [[ "$CETPKG_NAME" == *_MRB ]]; then
  [ "$CETPKG_NAME" = "${MRB_PROJECT}_MRB" ] || \
    { cat 1>&2 <<EOF
ERROR: mismatch between CETPKG_NAME ($CETPKG_NAME) and MRB_PROJECT ($MRB_PROJECT)
       Bad environment?
EOF
    exit 1
  }
  _mrb_alt=" (or \"mrb b\")"
  _to_build="MRB project \"$MRB_PROJECT\""
else
  _to_build="$CETPKG_NAME"
fi

cat <<EOF
Please use "buildtool"$_mrb_alt to configure and build $_to_build, e.g.:

  buildtool ${install_args[*]:+${install_args[*]} }-vTl [-jN]

See "buildtool --usage" (short usage help) or "buildtool -h|--help"
(full help) for more details.

EOF
