#!/bin/bash

[ -n "$CETPKG_SOURCE" ] && \
  [ -d "$CETPKG_SOURCE" ] && \
  [ -x "$CETPKG_SOURCE" ] && \
  [ -w "$CETPKG_SOURCE" ] || \
  { echo "CETPKG_SOURCE *must* be set and writable!" 1>&2; exit 1; }

cd "$CETPKG_SOURCE" || \
  { echo "unable to change directory to $CETPKG_SOURCE" 1>&2; exit 1; }

TMP=`mktemp -t perltidy-all.XXXXXX`
trap "rm $TMP* 2>/dev/null" EXIT

if type ack >/dev/null 2>&1; then
  cmd=(ack -f --print0 --perl)
else
  cmd=(find . -type f \!
       \( -name '*~' -o -name '*.new' -o -name '*.old' -o -name '*.orig'
       -o -name '*.bak' -o -name '*.tdy' -o -name '*.LOG' \) -print0)
  need_filter=1
fi
while IFS= read -r -d $'\0' file; do
  (( need_filter )) && \
    { file --mime-type "${file}" | grep -qi perl || continue; } >/dev/null 2>&1
  echo "Tidying Perl file $file"
  perltidy ${*:+"$@"} "$file"
done < <("${cmd[@]}")
