name: CMake Format Fix
run-name: '${{ github.actor }} fixing CMake format'

on:
  issue_comment:
    types:
      - created

permissions:
  pull-requests: write
  contents: write

jobs:
  parse-command:
    runs-on: ubuntu-latest
    name: Parse bot command
    if: >
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '@cetmodulesbot format')
    outputs:
      ref: ${{ steps.get_pr.outputs.ref }}
      sha: ${{ steps.get_pr.outputs.sha }}
      repo: ${{ steps.get_pr.outputs.repo }}

    steps:
      - name: Get PR Info
        id: get_pr
        uses: Framework-R-D/phlex/.github/actions/get-pr-info@a56582b6d7dbc26611b941a8d25ce36e8c32e950 # main

  apply_cmake_formatting:
    runs-on: ubuntu-latest
    name: Apply CMake formatting
    needs: parse-command
    if: ${{ needs.parse-command.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          path: cetmodules-src
          ref: ${{ needs.parse-command.outputs.ref }}
          repository: ${{ needs.parse-command.outputs.repo }}
          token: ${{ secrets.WORKFLOW_PAT }}

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.x'

      - name: Install gersemi
        run: pip install gersemi

      - name: Apply CMake formatting
        run: |
          echo "Applying CMake formatting..."
          gersemi -i cetmodules-src

      - name: Handle fix commit
        uses: Framework-R-D/phlex/.github/actions/handle-fix-commit@a56582b6d7dbc26611b941a8d25ce36e8c32e950 # main
        with:
          commit-message: 'Apply cmake-format fixes'
          working-directory: cetmodules-src
          token: ${{ secrets.WORKFLOW_PAT }}
          pr-info-ref: ${{ needs.parse-command.outputs.ref }}
          pr-info-repo: ${{ needs.parse-command.outputs.repo }}
